CREATE TABLE foodie_restaurants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant_name TEXT NOT NULL,
    rating INTEGER NOT NULL,
    meal TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);